package org.cryptocoinpartners.schema;

import org.joda.time.Instant;

import javax.annotation.Nullable;
import java.math.BigDecimal;


/**
 * Bars may be generated by subscribing a BarWindow to an Context then publishing Trades and Books to the Context
 *
 * @author Tim Olson
 */
public class BarOld extends Event {

    public BarOld( Instant time, Market market,
                BigDecimal open, BigDecimal high, BigDecimal low, BigDecimal close, @Nullable BigDecimal volume ) {
        super(time);
        this.open = open;
        this.high = high;
        this.low = low;
        this.close = close;
        this.volume = volume;
    }


    public BigDecimal getOpen() { return open; }
    public BigDecimal getHigh() { return high; }
    public BigDecimal getLow() { return low; }
    public BigDecimal getClose() { return close; }
    public @Nullable BigDecimal getVolume() { return volume; }


    private BigDecimal open;
    private BigDecimal high;
    private BigDecimal low;
    private BigDecimal close;
    private @Nullable BigDecimal volume;

}
