package org.cryptocoinpartners.schema;

import javax.persistence.*;
import java.util.UUID;


/**
 * @author Tim Olson
 */
@Inheritance(strategy = InheritanceType.TABLE_PER_CLASS)
@MappedSuperclass
public abstract class BaseEntity {


    @Id
    @Column( columnDefinition = "BINARY(16)", length = 16, updatable = false, nullable = false )
    public UUID getId() {
        ensureId();
        return id;
    }


    public boolean equals(Object o) {
        // generated by IDEA
        if( this == o ) return true;
        if( !(o instanceof BaseEntity) ) return false;
        BaseEntity that = (BaseEntity) o;
        return id.equals(that.id);
    }


    public int hashCode() {
        ensureId();
        return id.hashCode();
    }


    // JPA
    protected BaseEntity() {}
    protected void setId(UUID id) { this.id = id; }


    private void ensureId() {
        if( id == null )
            id = UUID.randomUUID();
    }


    private UUID id;
}
